version: '2'

services:
  frontend:
    build: ./../frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./../frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  service:
    build: ./../service
    ports:
      - '5050:5050'
    volumes:
      - /app/venv
      - ./../service:/app
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: knowledge_repo_dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowledge_repo_dev
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'

volumes:
  postgres_data:
